apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: {{ .Values.namespace }}
  labels:
    app: dex
    component: oauth
spec:
  type: ClusterIP
  ports:
{{- if and .Values.internalTls.enabled .Values.internalTls.dex }}
  - name: https
    port: 5554
    targetPort: https
{{- else }}
  - name: http
    port: 5556
    targetPort: http
{{- end }}
  selector:
    app: dex
    component: oauth