{{- if .Values.accessStrategy.createBearer }}
apiVersion: workspace.jupyter.org/v1alpha1
kind: WorkspaceAccessStrategy
metadata:
  name: bearer-access-strategy
  namespace: {{ .Values.accessStrategy.namespace }}
spec:
  displayName: JupyterLab Routing Strategy with bearer token authentication
  createConnectionHandler: "k8s-native"
  accessResourceTemplates:
    {{- if .Values.accessStrategy.createNetworkPolicy }}
    - kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      namePrefix: workspace-network-policy
      template: |
        spec:
          podSelector:
            matchLabels:
              workspace.jupyter.org/workspaceName: "{{`{{ .Workspace.Name }}`}}"
          policyTypes:
          - Ingress
          ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: {{ .Values.namespace }}
              podSelector:
                matchLabels:
                  app: traefik
                  component: router
            ports:
            - port: 8888
              protocol: TCP
          - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: jupyter-k8s-system
            ports:
            - port: 8888
              protocol: TCP
    {{- end }}
    - kind: IngressRoute
      apiVersion: traefik.io/v1alpha1
      namePrefix: authorized-route
      template: |
        spec:
          entryPoints:
            - websecure
          routes:
            - match: "Host(`{{ .Values.domain }}`) && PathPrefix(`/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}/`)"
              kind: Rule
              priority: 100
              middlewares:
                - name: auth-headers
                  namespace: {{ .Values.namespace }}
                - name: authmiddleware-verify
                  namespace: {{ .Values.namespace }}
              services:
                - name: "{{`{{ .Service.Name }}`}}"
                  namespace: "{{`{{ .Service.Namespace }}`}}"
                  port: 8888
    - kind: IngressRoute
      apiVersion: traefik.io/v1alpha1
      namePrefix: bearer-auth-route
      template: |
        spec:
          entryPoints:
            - websecure
          routes:
            - match: "Host(`{{ .Values.domain }}`) && PathPrefix(`/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}/bearer-auth`)"
              kind: Rule
              priority: 110
              middlewares:
                - name: auth-headers
                  namespace: {{ .Values.namespace }}
                - name: authmiddleware-bearer-auth
                  namespace: {{ .Values.namespace }}
                - name: strip-bearer-auth-suffix
                  namespace: {{ .Values.namespace }}
              services:
                - name: "{{`{{ .Service.Name }}`}}"
                  namespace: "{{`{{ .Service.Namespace }}`}}"
                  port: 8888
  deploymentModifications:
    podModifications:
      primaryContainerModifications:
        mergeEnv:
          - name: JUPYTER_BASE_URL
            valueTemplate: "/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}/"
  accessURLTemplate: "https://{{ .Values.domain }}/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}/"
  bearerAuthURLTemplate: "https://{{ .Values.domain }}/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}/bearer-auth"
  accessStartupProbe:
    httpGet:
      urlTemplate: "https://{{ .Values.domain }}/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}/bearer-auth"
      additionalSuccessStatusCodes: [400]
    initialDelaySeconds: 1
    periodSeconds: 2
    failureThreshold: 20
{{- end }}
