{{- $existingSecret := lookup "v1" "Secret" .Values.namespace "oauth2-proxy-cookie" -}}
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-cookie
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.oauth2Proxy.cookieSecret }}
  cookie-secret: {{ .Values.oauth2Proxy.cookieSecret | b64enc }}
  {{- else if and $existingSecret $existingSecret.data (index $existingSecret.data "cookie-secret") }}
  cookie-secret: {{ index $existingSecret.data "cookie-secret" }}
  {{- else }}
  cookie-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
