{{- if .Values.clusterWebUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-auth-middleware
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jupyter-k8s-aws-hyperpod.labels" . | nindent 4 }}
    app: authmiddleware
    component: auth
    workspace.jupyter.org/component: authmiddleware
spec:
  replicas: {{ .Values.clusterWebUI.auth.replicas }}
  selector:
    matchLabels:
      app: authmiddleware
      component: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  minReadySeconds: 0
  template:
    metadata:
      labels:
        {{- include "jupyter-k8s-aws-hyperpod.labels" . | nindent 8 }}
        app: authmiddleware
        component: auth
        workspace.jupyter.org/component: authmiddleware
    spec:
      serviceAccountName: jupyter-k8s-authmiddleware
      terminationGracePeriodSeconds: 30
      containers:
      - image: {{ .Values.clusterWebUI.auth.repository }}/{{ .Values.clusterWebUI.auth.imageName }}:{{ .Values.clusterWebUI.auth.imageTag }}
        imagePullPolicy: {{ .Values.clusterWebUI.auth.imagePullPolicy }}
        name: authmiddleware
        resources:
          requests:
            cpu: {{ .Values.clusterWebUI.auth.resources.requests.cpu }}
            memory: {{ .Values.clusterWebUI.auth.resources.requests.memory }}
          limits:
            cpu: {{ .Values.clusterWebUI.auth.resources.limits.cpu }}
            memory: {{ .Values.clusterWebUI.auth.resources.limits.memory }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 65532
          runAsGroup: 65532
        env:
          - name: PORT
            value: "8080"
          - name: NAMESPACE
            value: "{{ .Release.Namespace }}"
          - name: READ_TIMEOUT
            value: "{{ .Values.clusterWebUI.auth.readTimeout }}"
          - name: WRITE_TIMEOUT
            value: "{{ .Values.clusterWebUI.auth.writeTimeout }}"
          - name: SHUTDOWN_TIMEOUT
            value: "{{ .Values.clusterWebUI.auth.shutdownTimeout }}"
          - name: JWT_SECRET_NAME
            value: "{{ .Values.clusterWebUI.auth.secretName }}"
          - name: JWT_ISSUER
            value: "{{ .Values.clusterWebUI.auth.jwtIssuer }}"
          - name: JWT_AUDIENCE
            value: "{{ .Values.clusterWebUI.auth.jwtAudience }}"
          - name: JWT_EXPIRATION
            value: "{{ .Values.clusterWebUI.auth.jwtExpiration }}"
          - name: JWT_REFRESH_ENABLE
            value: "{{ .Values.clusterWebUI.auth.jwtRefreshEnable }}"
          - name: JWT_REFRESH_WINDOW
            value: "{{ .Values.clusterWebUI.auth.jwtRefreshWindow }}"
          - name: JWT_REFRESH_HORIZON
            value: "{{ .Values.clusterWebUI.auth.jwtRefreshHorizon }}"
          - name: NEW_KEY_USE_DELAY
            value: "{{ .Values.clusterWebUI.auth.jwtNewKeyUseDelay }}"
          - name: COOKIE_NAME
            value: "{{ .Values.clusterWebUI.auth.cookieName }}"
          - name: COOKIE_SECURE
            value: "{{ .Values.clusterWebUI.auth.cookieSecure }}"
          - name: COOKIE_DOMAIN
            value: "{{ .Values.clusterWebUI.domain }}"
          - name: COOKIE_PATH
            value: "{{ .Values.clusterWebUI.auth.cookiePath }}"
          - name: COOKIE_MAX_AGE
            value: "{{ .Values.clusterWebUI.auth.cookieMaxAge }}"
          - name: COOKIE_HTTP_ONLY
            value: "{{ .Values.clusterWebUI.auth.cookieHttpOnly }}"
          - name: COOKIE_SAME_SITE
            value: "{{ .Values.clusterWebUI.auth.cookieSameSite }}"
          - name: PATH_REGEX_PATTERN
            value: "{{ .Values.clusterWebUI.auth.pathRegexPattern }}"
          - name: ROUTING_MODE
            value: "{{ .Values.clusterWebUI.auth.routingMode }}"
          - name: WORKSPACE_NAME_SUBDOMAIN_REGEX
            value: "{{ .Values.clusterWebUI.auth.workspaceNameSubdomainRegex }}"
          - name: WORKSPACE_NAMESPACE_SUBDOMAIN_REGEX
            value: "{{ .Values.clusterWebUI.auth.workspaceNamespaceSubdomainRegex }}"
          - name: ENABLE_OAUTH
            value: "{{ .Values.clusterWebUI.auth.oauthEnabled }}"
          - name: ENABLE_BEARER_URL_AUTH
            value: "{{ .Values.clusterWebUI.auth.enableBearerAuth }}"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      securityContext:
        fsGroup: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
{{- end }}
