apiVersion: v2
name: jupyter-k8s-aws-oidc
description: AWS OIDC extension for jupyter-k8s (Traefik + Dex + OAuth2-Proxy)
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: "https://example.com/icon.png"

# Dependencies
# Require traefik CRDs to be installed (https://traefik.github.io/charts)
# Not adding as a dependency because of `helm` install issues
# Run `helm upgrade --install traefik-crd traefik/traefik-crds --version 1.15.0` first