{{- if and .Values.clusterWebUI.enabled .Values.clusterWebUI.rotator.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: authmiddleware-jwt-rotator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jupyter-k8s-aws-hyperpod.labels" . | nindent 4 }}
    app: authmiddleware-jwt-rotator
    component: security
spec:
  schedule: {{ include "hyperpod.rotationCronSchedule" . | quote | trim }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            {{- include "jupyter-k8s-aws-hyperpod.labels" . | nindent 12 }}
            app: authmiddleware-jwt-rotator
            component: security
        spec:
          serviceAccountName: authmiddleware-jwt-rotator
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            fsGroup: 65532
          containers:
          - name: rotator
            image: {{ .Values.clusterWebUI.rotator.repository }}/{{ .Values.clusterWebUI.rotator.imageName }}:{{ .Values.clusterWebUI.rotator.imageTag }}
            imagePullPolicy: {{ .Values.clusterWebUI.rotator.imagePullPolicy }}
            resources:
              requests:
                cpu: {{ .Values.clusterWebUI.rotator.resources.requests.cpu }}
                memory: {{ .Values.clusterWebUI.rotator.resources.requests.memory }}
              limits:
                cpu: {{ .Values.clusterWebUI.rotator.resources.limits.cpu }}
                memory: {{ .Values.clusterWebUI.rotator.resources.limits.memory }}
            securityContext:
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
            env:
            - name: SECRET_NAME
              value: "{{ .Values.clusterWebUI.auth.secretName }}"
            - name: SECRET_NAMESPACE
              value: "{{ .Values.namespace }}"
            - name: NUMBER_OF_KEYS
              value: "{{ .Values.clusterWebUI.rotator.numberOfKeys }}"
            - name: DRY_RUN
              value: "false"
{{- end }}
