apiVersion: workspace.jupyter.org/v1alpha1
kind: Workspace
metadata:
  name: ${WS_USER}-jupyterlab-private
  namespace: default
spec:
  displayName: "${WS_USER} JupyterLab Private"
  appType: jupyterlab
  desiredStatus: Running
  ownershipType: OwnerOnly
  accessType: OwnerOnly
  templateRef:
    name: sagemaker-jupyter-template
    namespace: jupyter-k8s-system
