apiVersion: workspace.jupyter.org/v1alpha1
kind: Workspace
metadata:
  name: ${WS_USER}-code-editor-public
  namespace: default
spec:
  displayName: "${WS_USER} Code Editor Public"
  appType: code-editor
  desiredStatus: Running
  ownershipType: Public
  accessType: Public
  templateRef:
    name: sagemaker-code-editor-template
    namespace: jupyter-k8s-system
