{{- if and .Values.webApp.enabled .Values.rotator.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-app-session-rotator
  namespace: {{ .Values.namespace }}
  labels:
    app: web-app-session-rotator
    component: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-app-session-rotator-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Values.webApp.session.secretName }}"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-app-session-rotator-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-app-session-rotator-role
subjects:
  - kind: ServiceAccount
    name: web-app-session-rotator
    namespace: {{ .Values.namespace }}
{{- end }}
