apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# AccessStrategies are shipped by the aws-oidc chart and must be deployed first.
resources:
  - workspace_with_access_strategy.yaml
  - workspace_with_access_strategy_private.yaml
  - workspace_with_bearer_access_strategy.yaml
  - workspace_with_bearer_access_strategy_private.yaml